### ISSUE TITLE
Is this like just your personal cloud storage?

### ISSUE THREAD

**Issue by Northo** [kaprests/miscellaneous#1]

**Comment by kaprests** [comment]
Sort of I guess. I think I just throw in stuff here that I might want to keep for some reason

**Comment by kaprests** [comment]
Like things that are unimportant, but maybe a little fun or cool for which it doesn't make sense to create a separate repo

**Comment by Northo** [comment]
yah, understand. Like the mandelbrot set

**Comment by kaprests** [comment]
Thanks for bringing this to my attention and opening this issue @Northo. Really glad we were able to clarify the purpose of this repository!

**Comment by hakonnoren** [comment]
@Northo, I think it is unnecessary to harass people like this. Whats nice about GitHub is that you can do want you want. No questions asked. Am I right? Leave @kaprests alone please.

**Comment by Northo** [comment]
@hakonnoren, I fear we might have gotten off on the wrong foot here. I have nothing but admiration for @kaprests' work, and as is clear from his comment, he was very glad for my comment.

> Thanks for bringing this to my attention and opening this issue @Northo. Really glad we were able to clarify the purpose of this repository!
