### ISSUE TITLE
Create a README.md

### ISSUE THREAD

**Issue by Northo** [kaprests/miscellaneous#2]

**Comment by Northo** [comment]
As the maintainer has not shown any interest in implementing the requested feature yet, I hope maybe a clarification of the expected implementation and intended purpose will accelerate the process.

# Implementation:
Creation of a file `README.md`, to be populated with text explaining the intent and structure of this repo.

# Purpose:
Give a user of the repo a clearer and more immediate understanding of the purpose and content of the repo. See issue #1.

**Comment by kaprests** [comment]
Right now I don't think there is need for a readme. Will reconsider in the future should the situation change
